global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'consciousness-backend'
    static_configs:
      - targets: ['consciousness-exporter:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3001']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'featherweight-app'
    static_configs:
      - targets: ['host.docker.internal:3000']
    scrape_interval: 10s
    metrics_path: '/metrics'
